Algoritmo "manzano1G"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gian Bueno
// Data atual  : 17/09/2024
Var
   soma, resultado, contadora: inteiro

Inicio
  contadora <- 1
  soma <- 1
  enquanto contadora <= 8 faça
  soma <- soma + resultado
  resultado <- resultado + soma
  contadora <- contadora +1
  fimenquanto
  escreval (soma)

Fimalgoritmo